development:
  sessions:
    default:
      hosts:
        - <%= ENV.fetch('DB_PORT_27017_TCP_ADDR', 'db') %>:<%= ENV.fetch('DB_PORT_27017_TCP_PORT', '27017') %>
      database: amber_development

test:
  sessions:
    default:
      hosts:
        - <%= ENV.fetch('DB_PORT_27017_TCP_ADDR', 'db') %>:<%= ENV.fetch('DB_PORT_27017_TCP_PORT', '27017') %>
      database: amber_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      hosts:
        - <%= ENV.fetch('DB_PORT_27017_TCP_ADDR', 'db') %>:<%= ENV.fetch('DB_PORT_27017_TCP_PORT', '27017') %>
      username: <%= ENV.fetch('MONGOID_USERNAME', '') %>
      password: <%= ENV.fetch('MONGOID_PASSWORD', '') %>
      database: <%= ENV.fetch('MONGOID_DATABASE', 'amberblog') %>
